spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dums
    username: postgres
    password: zhenghai
    driver-class-name: org.postgresql.Driver

logging:
  level:
    cn:
      celess:
        dums: debug